name: Lint PR Title

on:
  pull_request:
    types: [opened, reopened]

jobs:
  lint_pr_title:
    runs-on: self-hosted
    steps:
      - name: Check PR Title
        run: |
          title="${{ github.event.pull_request.title }}"
          echo "$title"
          exit 0
